Traceback (most recent call last):
  File "../../../../train_semi.py", line 19, in <module>
    from u2pl.dataset.augmentation import generate_unsup_data
  File "/home/jidian/sdb1/jinlei/U2PL/u2pl/dataset/augmentation.py", line 10, in <module>
    from scipy.ndimage import gaussian_filter
ModuleNotFoundError: No module named 'scipy'
Traceback (most recent call last):
  File "/home/jidian/anaconda3/envs/u2pl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jidian/anaconda3/envs/u2pl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jidian/anaconda3/envs/u2pl/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/jidian/anaconda3/envs/u2pl/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jidian/anaconda3/envs/u2pl/bin/python', '-u', '../../../../train_semi.py', '--local_rank=0', '--config=config1.yaml', '--seed', '2', '--port', '1255']' returned non-zero exit status 1.
