Traceback (most recent call last):
  File "../../../../train_semi.py", line 23, in <module>
    from u2pl.utils.loss_helper import ( compute_contra_memobank_loss, compute_unsupervised_loss,get_criterion,)
  File "/root/autodl-tmp/U2PL/u2pl/utils/loss_helper.py", line 7, in <module>
    from .utils import dequeue_and_enqueue
  File "/root/autodl-tmp/U2PL/u2pl/utils/utils.py", line 13, in <module>
    from skimage.measure import label, regionprops
ModuleNotFoundError: No module named 'skimage'
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/root/miniconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python', '-u', '../../../../train_semi.py', '--local_rank=0', '--config=config1.yaml', '--seed', '2', '--port', '1255']' returned non-zero exit status 1.
Killing subprocess 10524
